### ISSUE TITLE
Issue reading a email into another email

### ISSUE THREAD

**Issue by erika4448** [logankp/Deliverance#3]
Hi,

There is a problem when an email is attached to another email, causing the following error: "Cannot find item [__substg1.0_3701000D] within the current storage".

This is the stack Trace:
at OpenMcdf.CFStorage.GetStream(String streamName) in C:\Users\Federico\Desktop\OpenMcdf_t\sources\OpenMcdf\CFStorage.cs:line 198
   at Deliverance.OXMSG.StreamReaders.VariableLengthStreamReader.GetVariableLengthProperty(PropertyEntry entry, String storage) in D:\DskInst\Deliverance-master\Deliverance-master\Deliverance\OXMSG\StreamReaders\VariableLengthStreamReader.cs:line 42

I appreciate your collaboration with this issue!

Thanks :)

**Comment by logankp** [comment]
Thanks for submitting this! I didn't know people were actually using this library :)

That error doesn't surprise me, as email within email hasn't really been implemented yet. If I get some time I'll try to look into it.

**Comment by erika4448** [comment]
Hi! 

Yes , the library is great!!
I hope that in the not too distant future it will have this functionality...

thank you :)

**Comment by logankp** [comment]
@erika4448 Is there any chance you could provide the MSG file that you were using?
